name: Push Docker image
on:
  push:
    tags:
      - v*.*.**

jobs:
  build-and-push-seeker-image:
    name: Build Docker image for local ganache network
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dn3010/sylo-ethereum-testnet
          tags: type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build Tag and Push Docker image
        uses: docker/build-push-action@v5
        with:
          file: docker/ganache-with-protocol/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
